### ISSUE TITLE
sign in with friendica account not possible

### ISSUE THREAD

**Issue by foss-** [MozillaSocial/mozilla-social-android#348]
MoSo Nightly 1.0.27 Pre-release
Android 13.1
This is Friendica, version 2024.03-dev that is running at the web location https://pirati.ca. The database version is 1545/1545, the post update version is 1544/1544.

**Reproduce**

1. Choose a server
2. enter pirati.ca
3. webUI opens asking to `Authorize application connection`, confirm with `Yes`

**Currrently**

back a `Choose a server` screen, go in a loop

**Expected**

Accept login and authorization.

**Comment by JohnOberhauser** [comment]
Thanks for reporting this.  I've opened a PR to fix the issue https://github.com/MozillaSocial/mozilla-social-android/pull/349

**Comment by foss-** [comment]
Thanks for tackling this so swiftly. Sign-in works as expected in Nightly 0.1.0.30.
