### ISSUE TITLE
[Feature Request] multi account support

### ISSUE THREAD

**Issue by foss-** [MozillaSocial/mozilla-social-android#351]
Currently a single account can be used. Would be nice to add multi account support.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SOCAND-492)

**Comment by JohnOberhauser** [comment]
Added in 
https://github.com/MozillaSocial/mozilla-social-android/pull/511
https://github.com/MozillaSocial/mozilla-social-android/pull/513
https://github.com/MozillaSocial/mozilla-social-android/pull/514
