### ISSUE TITLE
app crashes when going to about

### ISSUE THREAD

**Issue by foss-** [MozillaSocial/mozilla-social-android#352]
MoSo Nightly 0.1.0.31 
Android 13.1

Thanks for https://github.com/MozillaSocial/mozilla-social-android/pull/350
However when going to `Account > Settings > About` the app crashes. Reproducible in all attempts.

**Comment by JohnOberhauser** [comment]
This should fix the crash https://github.com/MozillaSocial/mozilla-social-android/pull/354

However, the about screen will not load for friendica accounts until friendica implements the missing REST endpoints we use here

`/api/v2/instance`
`/api/v1/instance/extended_description`

These endpoints are not listed in friendica's implemented REST endpoints https://docs.friendi.ca/develop/spec/api/mastodon/#clients
