### ISSUE TITLE
Visual issues on the profile tab

### ISSUE THREAD

**Issue by cadeyrn** [MozillaSocial/mozilla-social-android#419]
_I am aware that the app is still early in development, and some things are probably already on your radar anyway. To make sure nothing gets missed, I'll open a series of issues with things I've noticed._

There are a few visual issues in the profile tab, which are basically all minor things, but I get stuck with my eye every time.

1. The tab label "Posts and Replies" is on two lines.
2) I'm not entirely happy with how the statistics are displayed (Followers - Following - Posts). I'm not sure what the perfect implementation looks like, but it all seems rather pushed to the left. Maybe make the font smaller and put everything in one line like the official Mastodon app? But the official Mastodon app only shows two stats as it shows the number of posts on a different place, so that could be difficult in terms of space.
3. the "Edit Profile" button is quite big and sticks to the cover picture.

![Screenshot_2024-01-28-10-13-41-42_45d8e3eaae3374bfcb41fa9e7b6b444c](https://github.com/MozillaSocial/mozilla-social-android/assets/1100614/cea270f5-9090-42ae-b683-d34abf056f78)

**Comment by JohnOberhauser** [comment]
Jira tickets SOCAND-431 and SOCAND-423

**Comment by JohnOberhauser** [comment]
fixed in https://github.com/MozillaSocial/mozilla-social-android/pull/426
