### ISSUE TITLE
Change of client name

### ISSUE THREAD

**Issue by cadeyrn** [MozillaSocial/mozilla-social-android#422]
_I am aware that the app is still early in development, and some things are probably already on your radar anyway. To make sure nothing gets missed, I'll open a series of issues with things I've noticed._

If you post something via the Android app, the client is identified as "MoSo Android":

<img width="336" alt="Bildschirmfoto 2024-01-28 um 10 36 16" src="https://github.com/MozillaSocial/mozilla-social-android/assets/1100614/fec632b5-a6f2-462c-b7c0-4902282a774c">

(Screenshot from the Mozilla Social web version)

I suggest changing it to "Mozilla Social Android" / "Mozilla.social Android" / "mozilla.social Android" (whatever your preferred spelling is) as having "Mozilla" in the name would be more clear than "MoSo". Also, it would be more consistent with the web version of Mozilla Social, which has "Mozilla.social" as client name.

Another possible advantage: If I didn't know Mozilla Social, I wouldn't think anything at all about "MoSo". With "Mozilla Social" on the other hand, I could think: _Oh, there's something from Mozilla? I'll take a look at that._ That's because Mozilla is a trusted brand.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SOCAND-485)

**Comment by JohnOberhauser** [comment]
Jira ticket SOCAND-429

**Comment by JohnOberhauser** [comment]
fixed in https://github.com/MozillaSocial/mozilla-social-android/pull/467
