### ISSUE TITLE
New profile tab for replies only

### ISSUE THREAD

**Issue by cadeyrn** [MozillaSocial/mozilla-social-android#450]
There are currently three tabs on the profile pages: "Posts", "Posts and Replies", and "Media". That's okay because it's exactly the same as what the official Mastodon app does.

But sometimes I'm just interested in seeing if an account is replying to other users, or I'm looking for a comment of my own that I know was a reply.

So I suggest adding a "Replies" tab. The advantage would also be that this would be a way to stand out from the official Mastodon app with another special feature (after the discover feature).

Threads, by the way, has exactly this feature. Even though I don't usually like Threads very much, maybe this at least confirms that I'm not the only one who sees a use case in this feature. 😄

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SOCAND-481)

**Comment by JohnOberhauser** [comment]
Unfortunately the mastodon api doesn't have an option for this
https://docs.joinmastodon.org/methods/accounts/#statuses
These are the available filters
- only media
- exclude replies
- exclude reposts
- only pinned
- posts with hashtag
